### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (768x3 and 1x307)

### ISSUE THREAD

**Issue by yinshuisiyuan123** [goaheand/AdapGL-pytorch#1]
请教一下作者大大，我的代码出现了这个错误：
Traceback (most recent call last):
  File "C:\Users\administrator1\Desktop\AdapGL-pytorch-master\AdapGL-pytorch-master\main.py", line 98, in <module>
    main(args)
  File "C:\Users\administrator1\Desktop\AdapGL-pytorch-master\AdapGL-pytorch-master\main.py", line 80, in main
    net_trainer.train(data_loaders[0], data_loaders[1])
  File "C:\Users\administrator1\Desktop\AdapGL-pytorch-master\AdapGL-pytorch-master\trainer\alt_trainer.py", line 173, in train
    self.train_one_epoch(train_data_loader, eval_data_loader, metrics, i)
  File "C:\Users\administrator1\Desktop\AdapGL-pytorch-master\AdapGL-pytorch-master\trainer\alt_trainer.py", line 131, in train_one_epoch
    self.model_pred_trainer.train(train_data_loader, eval_data_loader, metrics)
  File "C:\Users\administrator1\Desktop\AdapGL-pytorch-master\AdapGL-pytorch-master\trainer\alt_trainer.py", line 208, in train
    super().train(train_data_loader, eval_data_loader, metrics)
  File "C:\Users\administrator1\Desktop\AdapGL-pytorch-master\AdapGL-pytorch-master\utils\train_tool.py", line 35, in inner
    result = func(*args, **kwargs)
  File "C:\Users\administrator1\Desktop\AdapGL-pytorch-master\AdapGL-pytorch-master\trainer\base.py", line 56, in train
    self.train_one_epoch(train_data_loader)
  File "C:\Users\administrator1\Desktop\AdapGL-pytorch-master\AdapGL-pytorch-master\trainer\alt_trainer.py", line 197, in train_one_epoch
    pred = self.model(x, adj_mx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\administrator1\Desktop\AdapGL-pytorch-master\AdapGL-pytorch-master\models\AdapGL.py", line 285, in forward
    h = net_block(h, adj_mx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\administrator1\Desktop\AdapGL-pytorch-master\AdapGL-pytorch-master\models\AdapGL.py", line 226, in forward
    temporal_att = self.temporal_att(x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\administrator1\Desktop\AdapGL-pytorch-master\AdapGL-pytorch-master\models\ASTGCN.py", line 130, in forward
    y1 = self.w2(torch.matmul(x.transpose(2, 3), self.w1))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (768x3 and 1x307)
错误出现在ASTGCN的TemporalAttention模块， 
y1 = self.w2(torch.matmul(x.transpose(2, 3), self.w1))，self.w1的shape应该是（3， 307)啊,但是我自己debug下来self.w1的shape是（1， 307）

**Comment by yinshuisiyuan123** [comment]
![image](https://user-images.githubusercontent.com/91045571/216758143-4b626c04-d490-4449-97d8-a9091db636e7.png)

**Comment by goaheand** [comment]
你好！根据你所描述的数据集，self.w2.shape = (3, 307), 所以 y1.shape = (64, 12, 307) ; y2.shape = (64, 307, 12). 你的代码出现错误应该是由于输入 x 的 shape 不对，导致无法与 w1 相乘，希望对你有帮助！
